name: Deploy to Heroku
on: { push: { branches: [ "main" ] } }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm install
      - run: npm --prefix client install
      - run: npm --prefix server install
      - run: npm --prefix client run build
      - name: Push via Git to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          git remote add heroku https://heroku:${HRKU-AArwExBxlTQPvCJgvmuBrfvTngKQp5TpuPxtnQp5qbfQ_____wyifooCb2xP}@git.heroku.com/${oliver-dev-site}.git
          git push heroku HEAD:main -f
